services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager
    ports: 
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - <HOST_MOUNT_PATH>:/data
      - <HOST_MOUNT_PATH>:/etc/letsencrypt
    restart: unless-stopped