services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager
    ports: 
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./volumes/data:/data
      - ./volumes/letsencrypt:/etc/letsencrypt
    restart: unless-stopped